name: Build and Publish Project

on:
  # Trigger pipeline when new releases are made via git tags
  push:
    tags:
      - '*' # Triggers the workflow for any tag pushed
  # Allow manual running of pipeline
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: golemshaper/build

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update gh_pages
        run: |
          git checkout gh_pages --
          docker create cyber-athena -n cyber-athena
          docker cp cyber-athena:/app ./root
          git add .
          git commit -m "feat: Release $(date)"
          git push