name: Build and Publish Project

on:
  # Trigger pipeline when new releases are made via git tags
  push:
    tags:
      - '*' # Triggers the workflow for any tag pushed
  # Allow manual running of pipeline
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      # Permission to read from GHCR
      packages: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: golemshaper/build
        
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Extract Windows Build
        run: |
          ARTIFACT_DIR=$(mktemp -d)
          WINDOWS_ARTIFACT_DIR="${ARTIFACT_DIR}/windows"
          mkdir -p ${WINDOWS_ARTIFACT_DIR}

          CONTAINER_ID=$(docker create golemshaper/build:${{ github.ref_name }} --)
          
          echo "Extracting files from ${CONTAINER_ID} into ${WINDOWS_ARTIFACT_DIR}"
          docker cp ${CONTAINER_ID}:/app/windows/. "${WINDOWS_ARTIFACT_DIR}"

          echo "WINDOWS_ARTIFACT_DIR=${WINDOWS_ARTIFACT_DIR}" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          name: windows
          # A file, directory or wildcard pattern that describes what to upload
          path: "${{ env.WINDOWS_ARTIFACT_DIR }}"

      - name: Update gh_pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git checkout gh_pages --
          CONTAINER_ID=$(docker create golemshaper/build:${{ github.ref_name }} --)
          echo "Extracting files from ${CONTAINER_ID} into ./"
          docker cp ${CONTAINER_ID}:/app/wasm/. ./
          cp Rasterized3DEngineCyber.html index.html
          git add .
          git commit -m "feat: Release $(date)"
          git push